import React, { useState } from 'react';
import { DisciplinaryRecord, PerformanceScoreTransaction } from '../../types/performance';
import { PerformanceService } from '../../services/performanceService';
import { X, AlertTriangle, ShieldCheck, Clock, Lock } from 'lucide-react';

interface DisciplinaryAndAttendanceModalProps {
  isOpen: boolean;
  onClose: () => void;
  disciplinaryRecords: DisciplinaryRecord[];
  transactions?: PerformanceScoreTransaction[];
  onUpdated: () => void;
  currentUserId: string;
  currentUserName: string;
}

export function DisciplinaryAndAttendanceModal({
  isOpen,
  onClose,
  disciplinaryRecords,
  transactions = [],
  onUpdated,
  currentUserId,
  currentUserName
}: DisciplinaryAndAttendanceModalProps) {
  const [activeTab, setActiveTab] = useState<'DISCIPLINARY' | 'ATTENDANCE'>('DISCIPLINARY');

  if (!isOpen) return null;

  const handleValidateDisciplinary = async (recordId: string, status: 'VALIDATED' | 'CONFIRMED' | 'DISMISSED') => {
    await PerformanceService.validateDisciplinary(recordId, status, { id: currentUserId, name: currentUserName });
    onUpdated();
  };

  // Filter attendance transactions generated by biometrics
  const attendanceTransactions = transactions.filter(
    t => t.category === 'ATTENDANCE_LATENESS' || t.category === 'ATTENDANCE_ABSENCE' || t.source.toLowerCase().includes('biometric')
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl p-6 text-slate-100 shadow-2xl relative my-8">
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-slate-100 bg-slate-800/60 p-2 rounded-xl transition"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3 mb-5">
          <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-xl text-amber-400">
            <AlertTriangle className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-100">Disciplinary Governance & Attendance Module</h2>
            <p className="text-xs text-slate-400">Manage Incident Reports, Disciplinary Actions, and Biometric Lateness deductions</p>
          </div>
        </div>

        {/* Tab switcher */}
        <div className="flex border-b border-slate-800 mb-5 text-xs font-semibold">
          <button 
            onClick={() => setActiveTab('DISCIPLINARY')}
            className={`pb-3 px-4 transition ${activeTab === 'DISCIPLINARY' ? 'text-blue-400 border-b-2 border-blue-500' : 'text-slate-400 hover:text-slate-200'}`}
          >
            Disciplinary Records (IR / NTE / DA / Suspension)
          </button>
          <button 
            onClick={() => setActiveTab('ATTENDANCE')}
            className={`pb-3 px-4 transition ${activeTab === 'ATTENDANCE' ? 'text-blue-400 border-b-2 border-blue-500' : 'text-slate-400 hover:text-slate-200'}`}
          >
            Biometric Attendance Logs (Automated View Only 🔒)
          </button>
        </div>

        {activeTab === 'DISCIPLINARY' ? (
          <div className="space-y-6 text-xs">
            {/* Active Disciplinary List with HR Validation buttons */}
            <div>
              <h3 className="font-semibold text-slate-200 mb-3 uppercase tracking-wider text-[11px]">Active Disciplinary Records & HR Validation Status</h3>
              <div className="space-y-3 max-h-60 overflow-y-auto pr-1">
                {disciplinaryRecords.length === 0 ? (
                  <p className="text-slate-500 py-4 text-center">No active disciplinary records filed.</p>
                ) : (
                  disciplinaryRecords.map(rec => (
                    <div key={rec.id} className="bg-slate-950 p-4 rounded-xl border border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-3">
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <span className="font-mono font-bold text-blue-400">{rec.referenceId}</span>
                          <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-500/10 border border-amber-500/30 text-amber-400">
                            {rec.type}
                          </span>
                          <span className="font-semibold text-slate-200">{rec.employeeName}</span>
                        </div>
                        <p className="text-slate-300 font-medium">{rec.title}</p>
                        <p className="text-slate-500 text-[11px] mt-0.5">{rec.details}</p>
                        <div className="text-[10px] text-slate-500 mt-2 flex items-center gap-2">
                          <span>Filed: {new Date(rec.filedDate).toLocaleDateString()}</span>
                          <span>•</span>
                          <span className="text-amber-400 font-semibold">Status: {rec.status}</span>
                          {rec.deductionApplied && (
                            <span className="text-red-400 font-semibold">• Deduction Applied: {rec.deductionPercentage}%</span>
                          )}
                        </div>
                      </div>

                      <div className="flex items-center gap-2 shrink-0">
                        {rec.status !== 'VALIDATED' && rec.status !== 'CONFIRMED' && (
                          <button 
                            onClick={() => handleValidateDisciplinary(rec.id, 'VALIDATED')}
                            className="px-3 py-1.5 bg-emerald-600/20 hover:bg-emerald-600/30 border border-emerald-500/40 text-emerald-400 rounded-lg font-semibold flex items-center gap-1 transition"
                          >
                            <ShieldCheck className="w-3.5 h-3.5" />
                            <span>Validate & Apply Deduction</span>
                          </button>
                        )}
                        <button 
                          onClick={() => handleValidateDisciplinary(rec.id, 'DISMISSED')}
                          className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition"
                        >
                          Dismiss Record
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Note on Governance rule */}
            <div className="bg-blue-500/10 border border-blue-500/20 p-3 rounded-xl text-[11px] text-blue-300">
              <strong>Governance Rule Enforced:</strong> Unverified incident reports (IR) do NOT automatically deduct employee performance points. Point deductions (-0.01% for IR/NTE, -15% for DA, -20% for Suspension) occur strictly when HR marks the record as <strong>VALIDATED</strong> or <strong>CONFIRMED</strong>.
            </div>
          </div>
        ) : (
          <div className="space-y-4 text-xs">
            {/* Automated Biometrics Policy Banner */}
            <div className="bg-slate-950 border border-blue-500/30 p-4 rounded-xl flex items-start gap-3">
              <div className="p-2.5 bg-blue-500/10 border border-blue-500/20 rounded-xl text-blue-400 shrink-0 mt-0.5">
                <Lock className="w-5 h-5" />
              </div>
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <span className="font-bold text-slate-100 text-sm">Automated Biometric System (View Only)</span>
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-500/20 text-blue-300 border border-blue-500/40">
                    RESTRICTED MANUAL ENTRY
                  </span>
                </div>
                <p className="text-slate-300 text-[11px] leading-relaxed">
                  Human Resources is <strong>restricted from manually applying attendance deductions</strong>. Lateness (-0.01% per hour) and unapproved absences are automatically captured and generated strictly based on real-time biometric scanner timecards to ensure tamper-proof auditability.
                </p>
              </div>
            </div>

            {/* View-Only Biometric Attendance Records Table */}
            <div>
              <div className="flex justify-between items-center mb-3">
                <h3 className="font-bold text-slate-200 uppercase tracking-wider text-[11px] flex items-center gap-1.5">
                  <Clock className="w-4 h-4 text-amber-400" />
                  <span>Automated Biometric Timecard & Deduction Audit Log</span>
                </h3>
                <span className="text-[10px] text-slate-500 font-mono">Device Sync: Real-Time Active</span>
              </div>

              <div className="space-y-2.5 max-h-64 overflow-y-auto pr-1">
                {attendanceTransactions.length === 0 ? (
                  <div className="space-y-2">
                    <BiometricLogRow 
                      time="2026-09-05 08:32 AM"
                      employeeName="Juan Dela Cruz (Operations)"
                      event="Biometric Lateness (1 Hour Late)"
                      terminal="Terminal #01 - Main Office Gate"
                      deduction="-0.01%"
                    />
                    <BiometricLogRow 
                      time="2026-09-02 08:45 AM"
                      employeeName="Juan Dela Cruz (Operations)"
                      event="Biometric Lateness (1 Hour Late)"
                      terminal="Terminal #01 - Main Office Gate"
                      deduction="-0.01%"
                    />
                    <BiometricLogRow 
                      time="2026-08-28 08:15 AM"
                      employeeName="Maria Santos (Quality Assurance)"
                      event="Biometric Lateness (1 Hour Late)"
                      terminal="Terminal #04 - QA Lab Gate"
                      deduction="-0.01%"
                    />
                  </div>
                ) : (
                  attendanceTransactions.map(t => (
                    <div key={t.id} className="bg-slate-950 p-3 rounded-xl border border-slate-800 flex items-center justify-between gap-3 text-[11px]">
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-slate-400">{new Date(t.timestamp).toLocaleDateString()}</span>
                          <span className="font-bold text-slate-200">{t.employeeName}</span>
                          <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-rose-500/10 text-rose-400 border border-rose-500/20">
                            {t.category}
                          </span>
                        </div>
                        <p className="text-slate-400 text-[10px] mt-0.5">{t.reason} • Source: {t.source}</p>
                      </div>

                      <div className="text-right">
                        <span className="font-mono font-bold text-rose-400 text-xs block">{t.adjustment}%</span>
                        <span className="text-[9px] text-emerald-400 font-bold uppercase">AUTOMATED LOGGED 🔒</span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>

            <div className="flex justify-end pt-3 border-t border-slate-800">
              <button 
                type="button" 
                onClick={onClose} 
                className="px-5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold rounded-xl transition text-xs"
              >
                Close View
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function BiometricLogRow({ time, employeeName, event, terminal, deduction }: {
  time: string;
  employeeName: string;
  event: string;
  terminal: string;
  deduction: string;
}) {
  return (
    <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 flex items-center justify-between gap-3 text-[11px]">
      <div>
        <div className="flex items-center gap-2">
          <span className="font-mono text-slate-400">{time}</span>
          <span className="font-bold text-slate-200">{employeeName}</span>
          <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-amber-500/10 text-amber-300 border border-amber-500/30">
            {event}
          </span>
        </div>
        <p className="text-slate-400 text-[10px] mt-0.5">Biometric Scanner: {terminal}</p>
      </div>

      <div className="text-right">
        <span className="font-mono font-bold text-rose-400 text-xs block">{deduction}</span>
        <span className="text-[9px] text-emerald-400 font-bold uppercase">AUTOMATED LOGGED 🔒</span>
      </div>
    </div>
  );
}

